# Generated by Django 2.2.7 on 2022-05-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templateApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
