# Generated by Django 2.2.7 on 2022-05-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ecomp',
            field=models.CharField(default='Infosys', max_length=30),
        ),
    ]
